# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands

after-startup-command = ['exec-and-forget sketchybar']
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]
start-at-login = false
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'
accordion-padding = 0
default-root-container-orientation = 'auto'

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 4
    inner.vertical =   4
    outer.left =       4
    outer.bottom =     4
    outer.top =        30
    outer.right =      4

[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = ['layout floating', 'move-node-to-workspace 8']

[[on-window-detected]]
    if.app-id = 'com.tdesktop.Telegram'
    run = ['layout floating', 'move-node-to-workspace 9']

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-ctrl-shift-2 = 'move-node-to-workspace 2'
    alt-ctrl-shift-3 = 'move-node-to-workspace 3'
    alt-ctrl-shift-4 = 'move-node-to-workspace 4'
    alt-ctrl-shift-7 = 'move-node-to-workspace 7'
    alt-ctrl-shift-8 = 'move-node-to-workspace 8'
    alt-ctrl-shift-9 = 'move-node-to-workspace 9'

    alt-ctrl-shift-space = 'layout floating tiling'
    alt-ctrl-shift-s = 'exec-and-forget screencapture -i -c'
    
    cmd-h = [] # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"

    alt-ctrl-shift-c = 'reload-config'
    alt-ctrl-shift-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    enter = 'mode main'
    esc = 'mode main'